### ISSUE TITLE
Level #6 - Continuous Moving

### ISSUE THREAD

**Issue by ShalomPrinz** [ShalomPrinz/Pacman#6]
The ghosts and the Pacman won't stop moving. Both will move simultaneously. The Pacman will move according to the last button clicked, and the ghosts will keep moving randomly, but they won't stop moving.

**Comment by danprinz** [comment]
I think that ghosts should pick a direction randomly and keep moving that direction until it hits a wall, then again - pick different direction randomly. 
Otherwise you might find some ghost spinning around without any target. 
In future feature, you should consider making the ghosts smarter and “chase” Pac-Man.

**Comment by ShalomPrinz** [comment]
OK
